version: "3.2"
services:

  # Example build command: DOCKER_VERSION=18.06.1 DOCKER_COMPOSE_VERSION=1.22.0 PATCH=1 docker-compose build circleci_docker
  circleci_docker:
    image: circleci_docker
    build:
      context: circleci_docker/
      args:
        DOCKER_VERSION: ${DOCKER_VERSION}
        DOCKER_COMPOSE_VERSION: ${DOCKER_COMPOSE_VERSION}

  elasticsearch_curator:
    image: nyulibraries/elasticsearch_curator:5.5.4
    build: elasticsearch_curator/

  kubectl_aws_cli:
    image: nyulibraries/kubectl_aws_cli
    build: kubectl_aws_cli/

  wget:
    image: nyulibraries/wget:latest
    build: wget/
