version: "3.2"
services:

  # Example build command: DOCKER_VERSION=18.06.1-ce-git DOCKER_COMPOSE_VERSION=1.22.0 docker-compose build circleci_docker
  circleci_docker:
    image: nyulibraries/circleci_docker:${DOCKER_VERSION}-compose-${DOCKER_COMPOSE_VERSION}
    build:
      context: circleci_docker/
      args:
        DOCKER_VERSION: ${DOCKER_VERSION}
        DOCKER_COMPOSE_VERSION: ${DOCKER_COMPOSE_VERSION}

  elasticsearch_curator: 
    image: nyulibraries/elasticsearch_curator:5.5.4
    build: elasticsearch_curator/

  kubectl_aws_cli:
    image: nyulibraries/kubectl_aws_cli
    build: kubectl_aws_cli/

  nginx:
    image: nyulibraries/nginx:1.15.5-alpine
    build:
      context: nginx/
      args:
      - AQUA_MICROSCANNER_TOKEN

  wget:
    image: nyulibraries/wget:latest
    build: wget/
