version: "3.2"
services:

  circleci_docker:
    image: nyulibraries/circleci_docker:18.06.1-ce-git
    build:
      context: circleci_docker/
      args:
        DOCKER_VERSION: 18.06.1-ce-git

  kubectl_aws_cli:
    image: nyulibraries/kubectl_aws_cli
    build: kubectl_aws_cli/

  wget:
    image: nyulibraries/wget:latest
    build: wget/
